#!/bin/sh
# Reference solution: repair all 119 seeded defects in the agent-visible checkout.
#   sh solve.sh [CHECKOUT]    (default: $WORKDIR, else /workspace)
# Each EDITS row is [defect, file, seeded text, repaired text]: the manifest's
# `new` -> `old` replacement, plus N01's centered-offset setup line. Every seeded
# text must occur exactly once when its row is applied, so a second run fails.
# Rebuild: python3 -B -m bug_competition.grader.tests.build_reference_solution
set -eu
cd "${1:-${WORKDIR:-/workspace}}"
python3 -B -c '
import json, sys
from pathlib import Path
for ident, name, seeded, repaired in json.load(sys.stdin):
    path = Path(name)
    text = path.read_bytes().decode("utf-8")
    if text.count(seeded) != 1:
        sys.exit(f"{ident}: seeded text is not unique in {name}")
    path.write_bytes(text.replace(seeded, repaired, 1).encode("utf-8"))
' <<'EDITS'
[
["E01", "mosslight/engine.py", "return SEASONS[(day // 12 + 1) % 4]", "return SEASONS[(day // 12) % 4]"],
["E02", "mosslight/engine.py", "neighbor_mean = sum(world.cells[world.index(a, b)].moisture for a, b in neighbors(world, x, y)) // len(adjacent)", "neighbor_mean = sum(n.moisture for n in adjacent) // len(adjacent)"],
["E03", "mosslight/engine.py", "comfort = 8 - abs(cell.moisture - desired_moisture) // 9 - abs(cell.shade - desired_shade) // 13", "comfort = 8 - abs(cell.moisture - desired_moisture) // 9 - abs(shade - desired_shade) // 13"],
["E04", "mosslight/engine.py", "cell.nutrients = clamp(before.nutrients)", "cell.nutrients = clamp(before.nutrients + (1 if before.species is None else 0))"],
["E05", "mosslight/engine.py", "cell.nutrients = clamp(before.nutrients - upkeep + (2 if before.vitality < 25 else 0))", "cell.nutrients = clamp(cell.nutrients - upkeep + (2 if cell.vitality < 25 else 0))"],
["E06", "mosslight/engine.py", "if cell.vitality == 0 or cell.age > 105:", "if cell.vitality == 0 or cell.age > (75 if before.species == \"glowcap\" else 105):"],
["E07", "mosslight/engine.py", "if season_name == \"Hush\":\n                    comfort -= 2", "if season_name == \"Hush\" and before.species != \"glowcap\":\n                    comfort -= 2"],
["E08", "mosslight/habitat.py", "for a, b in ((x, y), (x-1, y), (x+1, y), (x, y-1)):", "for a, b in ((x, y), (x-1, y), (x+1, y), (x, y-1), (x, y+1)):"],
["E09", "mosslight/habitat.py", "if tile[\"structure\"] == \"rain_barrel\":", "if tile[\"structure\"] == \"rain_barrel\" and rain:"],
["E10", "mosslight/habitat.py", "\"fireflies\": int(glowing / 2 + 0.5)", "\"fireflies\": glowing//2"],
["E11", "mosslight/habitat.py", "t[\"terrain\"] == \"soil\"", "t[\"terrain\"] in (\"soil\", \"peat\")"],
["E12", "mosslight/habitat.py", "if world.day % 3 == 0 and tile[\"mulch\"] > 0:\n                cell.nutrients = min(100, cell.nutrients + 1)", "if world.day % 3 == 0:\n                cell.nutrients = min(100, cell.nutrients + 1)"],
["E13", "mosslight/habitat.py", "tile[\"stress\"] = min(100, tile[\"stress\"]+5) if cell.vitality <= 30 else max(0, tile[\"stress\"]-3)", "tile[\"stress\"] = min(100, tile[\"stress\"]+5) if cell.vitality < 30 else max(0, tile[\"stress\"]-3)"],
["E14", "mosslight/gardening.py", "for x in range(left, right)", "for x in range(left, right+1)"],
["E15", "mosslight/gardening.py", "if shape == \"circle\" and dx+dy > radius:", "if shape == \"circle\" and dx*dx+dy*dy > radius*radius:"],
["E16", "mosslight/gardening.py", "world.workbench[\"tiles\"][source_index][\"stress\"] = 0\n    tile[\"stress\"] = 0", "tile[\"stress\"] = world.workbench[\"tiles\"][source_index][\"stress\"]\n    world.workbench[\"tiles\"][source_index][\"stress\"] = 0"],
["E17", "mosslight/gardening.py", "cell.age = cell.age-5", "cell.age = max(0, cell.age-5)"],
["E18", "mosslight/gardening.py", "cell.vitality = cell.vitality+8", "cell.vitality = min(100, cell.vitality+8)"],
["E19", "mosslight/gardening.py", "cell.age = max(0, cell.age-5)\n    cell.vitality = max(1, cell.vitality-15)", "cell.age = 0\n    cell.vitality = max(1, cell.vitality-15)"],
["E20", "mosslight/gardening.py", "if stock[key] < cost:", "if stock[key] < cost*amount:"],
["E21", "mosslight/nursery.py", "batch[\"hydration\"] = min(3,batch[\"hydration\"]+1)", "batch[\"hydration\"] = 3"],
["E22", "mosslight/nursery.py", "batch[\"vitality\"] = min(100,batch[\"vitality\"]+(3 if batch[\"status\"] == \"growing\" else 0))", "batch[\"vitality\"] = min(100,batch[\"vitality\"]+3)"],
["E23", "mosslight/nursery.py", "batch[\"age\"] += 1\n            batch[\"vitality\"] = max(0,batch[\"vitality\"]-20)", "batch[\"vitality\"] = max(0,batch[\"vitality\"]-20)"],
["E24", "mosslight/nursery.py", "cell.nutrients = max(0,cell.nutrients-4) if batch[\"count\"] == 1 else cell.nutrients", "cell.nutrients = max(0,cell.nutrients-4)"],
["E25", "mosslight/planning.py", "if any(b[\"name\"] == name for b in world.workbench[\"beds\"]):", "if any(b[\"name\"].casefold() == name.casefold() for b in world.workbench[\"beds\"]):"],
["E26", "mosslight/planning.py", "integer(day, \"Scheduled day\", world.day+2)", "integer(day, \"Scheduled day\", world.day+1)"],
["E27", "mosslight/planning.py", "tend_many(world, entry[\"tiles\"], entry[\"action\"])", "tend_many(world, entry[\"tiles\"], entry[\"action\"])\n            # tend_many replaces state, so retrieve the entry again.\n            entry = find_entry(world, \"plans\", ident)"],
["E28", "mosslight/planning.py", "p[\"status\"] == \"pending\" and p[\"day\"] == world.day", "p[\"status\"] == \"pending\" and p[\"day\"] <= world.day"],
["E29", "mosslight/planning.py", "failed = set()\n    for rule in sorted(world.workbench[\"rules\"], key=lambda r: r[\"id\"]):\n        if not rule[\"enabled\"]:\n            continue\n        for x, y in rule[\"tiles\"]:\n            value = getattr(world.cell(x, y), rule[\"metric\"])\n            applies = value < rule[\"threshold\"] if rule[\"operator\"] == \"below\" else value > rule[\"threshold\"]\n            if applies:\n                try:\n                    act(world, x, y, rule[\"action\"])\n                except ValueError:\n                    failed.add(rule[\"id\"])", "matches = []\n    for rule in sorted(world.workbench[\"rules\"], key=lambda r: r[\"id\"]):\n        if not rule[\"enabled\"]:\n            continue\n        for x, y in rule[\"tiles\"]:\n            value = getattr(world.cell(x, y), rule[\"metric\"])\n            applies = value < rule[\"threshold\"] if rule[\"operator\"] == \"below\" else value > rule[\"threshold\"]\n            if applies:\n                matches.append((rule[\"id\"], x, y, rule[\"action\"]))\n    failed = set()\n    for ident, x, y, action in matches:\n        try:\n            act(world, x, y, action)\n        except ValueError:\n            failed.add(ident)"],
["E30", "mosslight/engine.py", "return day % 47", "return day % 48"],
["F01", "mosslight/analysis.py", "\"coverage\": round(100*len(living)/len(cells), 1)", "\"coverage\": round(100*len(living)/len(cells), 2)"],
["F02", "mosslight/analysis.py", "round(sum(c.vitality for c in living)/len(cells), 2) if living else 0", "round(sum(c.vitality for c in living)/len(living), 2) if living else 0"],
["F03", "mosslight/analysis.py", "-sum(p*math.log2(p) for p in proportions)", "-sum(p*math.log(p) for p in proportions)"],
["F04", "mosslight/analysis.py", "shade = cell.shade", "shade = effective_shade(world, index)"],
["F05", "mosslight/analysis.py", "if world.cell(x,y).species:", "if empty_only and world.cell(x,y).species:"],
["F06", "mosslight/analysis.py", "if world.workbench[\"tiles\"][i][\"stress\"] > 50:", "if world.workbench[\"tiles\"][i][\"stress\"] >= 50:"],
["F07", "mosslight/analysis.py", "return sorted(result, key=lambda p: (p[\"size\"], p[\"tiles\"][0][1], p[\"tiles\"][0][0]))", "return sorted(result, key=lambda p: (-p[\"size\"], p[\"tiles\"][0][1], p[\"tiles\"][0][0]))"],
["F08", "mosslight/analysis.py", "if double > dy:", "if double >= dy:"],
["F09", "mosslight/analysis.py", "if offset % every == 0:", "if offset % every == 0 or offset == days:"],
["F10", "mosslight/notebook.py", "any(tag in item for item in n[\"tags\"])", "tag in n[\"tags\"]"],
["F11", "mosslight/notebook.py", "start <= n[\"day\"] < end", "start <= n[\"day\"] <= end"],
["F12", "mosslight/notebook.py", "\"tile\": [x, y], **{k:v for k,v in cell.to_dict().items() if k != \"vitality\"}", "\"tile\": [x, y], **cell.to_dict()"],
["F13", "mosslight/notebook.py", "(status == \"overdue\" and t[\"due\"] <= world.day)", "(status == \"overdue\" and t[\"due\"] < world.day)"],
["F14", "mosslight/notebook.py", "entry[\"done\"] = True", "entry[\"done\"] = done"],
["F15", "mosslight/notebook.py", "sorted(selected, key=lambda t: t[\"id\"])", "sorted(selected, key=lambda t: (t[\"due\"], t[\"id\"]))"],
["F16", "mosslight/weather.py", "\"season_day\":(day+1)%12+1", "\"season_day\":day%12+1"],
["F17", "mosslight/weather.py", "wetness = (0.46,0.20,0.31,0.37)[(day//12+1)%4]", "wetness = (0.46,0.20,0.31,0.37)[(day//12)%4]"],
["F18", "mosslight/weather.py", "current = current+1 if entry[\"rainfall\"] == 8 else 0", "current = current+1 if entry[\"rainfall\"] == 0 else 0"],
["F19", "mosslight/weather.py", "for entry in almanac(world,within,start=world.day)[\"days\"]:", "for entry in almanac(world,within)[\"days\"]:"],
["F20", "mosslight/weather.py", "gap//plan[\"repeat\"] <= plan[\"remaining\"]", "gap//plan[\"repeat\"] < plan[\"remaining\"]"],
["F21", "mosslight/experiments.py", "if event[\"offset\"] <= offset:", "if event[\"offset\"] == offset:"],
["F22", "mosslight/experiments.py", "if offset%every == 0:", "if offset%every == 0 or offset == days:"],
["F23", "mosslight/experiments.py", "delta = compare(trial,worlds[0])", "delta = compare(worlds[0],trial)"],
["F24", "mosslight/experiments.py", "rows.sort(key=lambda r:(-r[\"value\"],r[\"name\"]))", "rows.sort(key=lambda r:-r[\"value\"])"],
["F25", "mosslight/experiments.py", "if name in names:", "if name.casefold() in names:"],
["F26", "mosslight/exchange.py", "trial = World.from_dict(trial.to_dict())\n    trial.revision = world.revision+1\n    trial.revision += 1", "trial = World.from_dict(trial.to_dict())\n    trial.revision = world.revision+1"],
["F27", "mosslight/exchange.py", "tile[\"x\"] = width-tile[\"x\"]", "tile[\"x\"] = width-1-tile[\"x\"]"],
["F28", "mosslight/exchange.py", "tile[\"x\"],tile[\"y\"] = height-tile[\"y\"],tile[\"x\"]", "tile[\"x\"],tile[\"y\"] = height-1-tile[\"y\"],tile[\"x\"]"],
["F29", "mosslight/exchange.py", "for task in world.workbench[\"tasks\"]:", "for task in sorted(world.workbench[\"tasks\"],key=lambda t:(t[\"due\"],t[\"id\"])):"],
["F30", "mosslight/charts.py", "int(a+(b-a)*value):02x", "round(a+(b-a)*value):02x"],
["F31", "mosslight/charts.py", "value = settings[layer] if layer in (\"terrain\",\"mulch\",\"stress\") else cell.shade if layer == \"shade\" else getattr(cell,layer)", "value = settings[layer] if layer in (\"terrain\",\"mulch\",\"stress\") else effective_shade(world,i) if layer == \"shade\" else getattr(cell,layer)"],
["F32", "mosslight/charts.py", "first,last = 0,len(history)-1", "first,last = history[0][\"day\"],history[-1][\"day\"]"],
["P01", "mosslight/model.py", "or not isinstance(y, int)", "or isinstance(x, bool) or not isinstance(y, int) or isinstance(y, bool)"],
["P02", "mosslight/model.py", "\"journal\": list(self.journal), \"workbench\": copy.deepcopy(self.workbench),", "\"journal\": copy.deepcopy(self.journal), \"workbench\": copy.deepcopy(self.workbench),"],
["P03", "mosslight/model.py", "cells, list(journal), weather, revision)", "cells, copy.deepcopy(journal), weather, revision)"],
["P04", "mosslight/model.py", "species is None and (values[3] and values[4])", "species is None and (values[3] or values[4])"],
["P05", "mosslight/model.py", "or data.get(\"version\") not in (1, SAVE_VERSION)", "or type(data.get(\"version\")) is not int or data.get(\"version\") not in (1, SAVE_VERSION)"],
["P06", "mosslight/state.py", "raw = {key: value for key, value in raw.items() if key not in unknown}", "raise ValueError(f\"Unknown workbench fields: {', '.join(sorted(unknown))}\")"],
["P07", "mosslight/state.py", "for name in (\"notes\", \"specimens\", \"tasks\", \"beds\", \"plans\", \"rules\", \"nursery\"):\n        ids = set()\n        for item", "for name in (\"notes\", \"specimens\", \"tasks\", \"beds\", \"plans\", \"rules\", \"nursery\"):\n        for item"],
["P08", "mosslight/state.py", "ident > state[\"next_id\"]", "ident >= state[\"next_id\"]"],
["P09", "mosslight/state.py", "if point[\"day\"] < previous_day:", "if point[\"day\"] <= previous_day:"],
["P10", "mosslight/state.py", "if tile[\"terrain\"] == \"pond\" and cell.species is not None:", "if not TERRAINS[tile[\"terrain\"]][\"plantable\"] and cell.species is not None:"],
["P11", "mosslight/state.py", "state.update(raw.copy())", "state.update(copy.deepcopy(raw))"],
["P12", "mosslight/commands.py", "if not {\"op\"}.issubset(command):", "if set(command) - {\"op\",\"args\"}:"],
["P13", "mosslight/commands.py", "trial.revision = trial.revision+1", "trial.revision = world.revision+1"],
["P14", "mosslight/server.py", "if self.save_path:\n            self.world = trial\n            save(trial, self.save_path)\n        if history:", "if self.save_path:\n            save(trial, self.save_path)\n        if history:"],
["P15", "mosslight/server.py", "self.undo_stack = self.undo_stack[:30]", "self.undo_stack = self.undo_stack[-30:]"],
["P16", "mosslight/server.py", "self.redo_stack = self.redo_stack[-30:]", "self.redo_stack.clear()"],
["P17", "mosslight/server.py", "body[\"revision\"] < self.server.world.revision", "body[\"revision\"] != self.server.world.revision"],
["P18", "mosslight/server.py", "not isinstance(body[\"revision\"], int)", "type(body[\"revision\"]) is not int"],
["P19", "mosslight/server.py", "if \"world\" in body:\n                        trial.revision = self.server.world.revision+1", "if \"revision\" in body:\n                        trial.revision = self.server.world.revision+1"],
["P20", "mosslight/server.py", "trial = World.from_dict(copy.deepcopy(source[-1]))\n                    trial.revision = trial.revision+1", "trial = World.from_dict(copy.deepcopy(source[-1]))\n                    trial.revision = self.server.world.revision+1"],
["P21", "mosslight/__main__.py", "return 1\n\n\nif __name__", "return 2\n\n\nif __name__"],
["P22", "mosslight/__main__.py", "if args.output == args.path:", "if Path(args.output).resolve() == Path(args.path).resolve():"],
["P23", "mosslight/render.py", "attrs = 'tabindex=\"0\" role=\"button\"'", "attrs = 'tabindex=\"0\" role=\"button\"' if interactive else ''"],
["P24", "mosslight/courier.py", "for peer in b.keys())", "for peer in a.keys() | b.keys())"],
["P25", "mosslight/courier.py", "counter = packet[\"counter\"] + 1", "counter = max(packet[\"counter\"], packet[\"clock\"].get(peer, 0)) + 1"],
["P26", "mosslight/courier.py", "\"value\": value,", "\"value\": copy.deepcopy(value),"],
["P27", "mosslight/courier.py", "if left[\"events\"][key][\"record\"] != right[\"events\"][key][\"record\"]:", "if left[\"events\"][key] != right[\"events\"][key]:"],
["P28", "mosslight/courier.py", "if not alive or any(event[\"value\"] is False for event in alive):", "if not any(event[\"value\"] is True for event in alive):"],
["P29", "mosslight/courier.py", "json.dumps(event[\"value\"], ensure_ascii=False, sort_keys=True).casefold(): event[\"value\"]", "json.dumps(event[\"value\"], ensure_ascii=False, sort_keys=True): event[\"value\"]"],
["P30", "mosslight/courier.py", "context = {peer: max(values.get(peer, 0) for values in packet[\"contexts\"].values())\n               for peer in set().union(*(values.keys() for values in packet[\"contexts\"].values()))}", "context = packet[\"contexts\"].get(event[\"record\"], {})"],
["P31", "mosslight/courier.py", "result[\"contexts\"] = dict(result[\"contexts\"])", "result[\"contexts\"] = {record: context for record, context in result[\"contexts\"].items() if record in requested}"],
["P32", "mosslight/courier.py", "max((acks.get(peer, {}).get(writer, 0) for peer in peers), default=0)", "min((acks.get(peer, {}).get(writer, 0) for peer in peers), default=0)"],
["P34", "mosslight/courier.py", "\"context\": dict(packet[\"clock\"])}", "\"context\": record_clock(packet, record)}"],
["P34", "mosslight/courier.py", "record: _join(packet[\"contexts\"].get(record, {}), packet[\"clock\"])", "record: record_clock(packet, record)"],
["X01", "mosslight/runtime.py", "return CURRENT_VERSION", "return definition[\"runtime\"][\"id\"]"],
["V01", "mosslight/campaigns.py", "AND (generation = ? OR owner != ?) AND status = 'running'\"\"\",\n                (_json(state)", "AND generation = ? AND owner = ? AND status = 'running'\"\"\",\n                (_json(state)"],
["V02", "mosslight/campaigns.py", "if offset <= event[\"offset\"] <= offset + days:", "if offset < event[\"offset\"] <= offset + days:"],
["V03", "mosslight/campaigns.py", "if row[\"offset\"] in (-1, 0, definition[\"days\"]) or row[\"offset\"] % keep_every == 0:", "if row[\"offset\"] in (-1, 0, definition[\"days\"]) or row[\"offset\"] % keep_every == 0 or key in protected:"],
["V04", "mosslight/campaigns.py", "if accepted:\n                self.db.execute(\"COMMIT\")\n                self.db.execute(\"BEGIN IMMEDIATE\")\n                self._checkpoint(claim[\"campaign\"], claim[\"ordinal\"], state)", "if accepted:\n                self._checkpoint(claim[\"campaign\"], claim[\"ordinal\"], state)"],
["X02", "mosslight/history.py", "command[\"args\"][\"ident\"] = event[\"bindings\"].get(\"ident\", entity[\"id\"])", "command[\"args\"][\"ident\"] = entity[\"id\"]"],
["H01", "mosslight/history.py", "return _digest({\"root\": root[\"id\"], \"engine\": root[\"engine\"], \"events\": events[-1:]})", "return _digest({\"root\": root[\"id\"], \"engine\": root[\"engine\"], \"events\": events})"],
["H02", "mosslight/history.py", "def _pick_identity(event):\n    return _digest(event[\"command\"])", "def _pick_identity(event):\n    return event[\"id\"]"],
["H03", "mosslight/history.py", "base_revision = self._branch(source[\"parent\"])[\"head\"]", "base_revision = source[\"base_revision\"]"],
["H04", "mosslight/history.py", "before = original[\"result\"]", "before = self._replay(root, original[\"events\"][:index])"],
["H05", "mosslight/history.py", "for sequence in (target,):", "for sequence in (target, local):"],
["H06", "mosslight/history.py", "return left == right", "return left[\"command\"] == right[\"command\"]"],
["L01", "mosslight/ensembles.py", "checked_reads = {key: ticket[\"inputs\"][key][\"digest\"] for key in ticket[\"known_reads\"]}", "checked_reads = computed[\"reads\"]"],
["R01", "mosslight/ensemble_reports.py", "pairs = list(zip(controls.values(), [rows[replicate] for replicate in paired_ids]))", "pairs = [(controls[replicate], rows[replicate]) for replicate in paired_ids]"],
["R02", "mosslight/ensembles.py", "envelope = json.loads(row[0])\n        envelope[\"result\"] = summarize(workspace[\"definition\"], self._outcomes(ensemble))\n        envelope[\"result_digest\"] = digest(envelope[\"result\"])\n        return envelope", "envelope = json.loads(row[0])\n        return envelope"],
["R03", "mosslight/ensemble_compute.py", "identity = copy.deepcopy(cached[\"origin\"][\"identity\"]) if cached is not None else requested_identity", "identity = requested_identity"],
["M01", "mosslight/save_merge.py", "return _encoded([\"base\", ident])", "return _encoded([\"base\", ident] if ident in base_ids else [origin, ident])"],
["X03", "mosslight/history_exchange.py", "        return maximal[:1]\n", "        return maximal\n"],
["Q01", "mosslight/studies.py", "if not support[\"common\"]:", "if not support[\"terminal\"]:"],
["Q02", "mosslight/studies.py", "parent = self.checkpoint(study, index - 1, replicate, \"control\")", "parent = self.checkpoint(study, index - 1, replicate, treatment)"],
["N01", "mosslight/field_calibration.py", "    times = [t for t, _ in values]\n    total = math.fsum(times)\n    spread = math.fsum(t*t for t in times) - total*total/len(times)\n    covariance = math.fsum(t*y for t,y in values) - total*math.fsum(ys)/len(times)\n    slope = covariance/spread if spread > 0 else 0.0", "    spread = math.fsum((x-center)**2 for x in xs)\n    slope = math.fsum((x-center)*(y-mean) for x,y in zip(xs,ys))/spread if spread else 0.0"],
["N01", "mosslight/field_calibration.py", "    center = math.fsum(t - origin for t, _ in values)/len(values)\n", "    xs = [t - origin for t, _ in values]\n    center = math.fsum(xs)/len(xs)\n"],
["N02", "mosslight/workspace_catalog.py", "        self.db.execute('REINDEX catalog_by_label')\n        self._install_key(CURRENT_FORMAT)", "        self._install_key(CURRENT_FORMAT)\n        self.db.execute('REINDEX catalog_by_label')"],
["I01", "mosslight/irrigation_flow.py", "if edge.capacity <= 0 or edge.end in seen or edge.pipe is None:", "if edge.capacity <= 0 or edge.end in seen:"],
["I02", "mosslight/irrigation.py", "return encoded({'measurement':census(_world(state['world'])),'offset':state['offset'],'remaining':state['remaining']})", "return encoded({'world':state['world'],'offset':state['offset'],'remaining':state['remaining']})"]
]
EDITS
